import sys
import os
from pathlib import Path

from PySide6.QtCore import QSettings, Signal

from PySide6.QtWidgets import (
    QApplication, QMainWindow, QWidget, QHBoxLayout, QVBoxLayout,
    QGraphicsView, QGraphicsScene, QGroupBox, QFormLayout, QLabel,
    QSlider, QPushButton, QFileDialog, QMessageBox, QButtonGroup,
    QStatusBar, QSizePolicy, QSplitter, QCheckBox, QFrame,
)
from PySide6.QtCore import Qt, QRectF, QByteArray
from PySide6.QtGui import (
    QImage, QPixmap, QPainter, QColor, QBrush, QPen,
    QDragEnterEvent, QDropEvent, QWheelEvent, QMouseEvent,
    QKeySequence, QAction, QDesktopServices,
)
from PySide6.QtCore import QUrl
import numpy as np

from dds_decoder import parse_dds, DDSInfo


APP_VERSION = "1.1"

try:
    from build_info import BUILD_HASH, BUILD_DATE  # generated by build.py
except ImportError:
    BUILD_HASH = "dev"
    BUILD_DATE = "local"

APP_TITLE = f"EZ DDS Viewer v{APP_VERSION} ({BUILD_HASH})"

CHECKER_DARK  = QColor(160, 160, 160)
CHECKER_LIGHT = QColor(200, 200, 200)
CHECKER_SIZE  = 16


def _is_newer_version(remote: str, local: str) -> bool:
    """Compare dot-separated version strings (e.g. '1.2.3'). Returns True if
    remote > local. Non-numeric segments fall back to lexicographic compare."""
    def parts(s):
        out = []
        for seg in s.strip().lstrip("v").split("."):
            try:
                out.append((0, int(seg)))
            except ValueError:
                out.append((1, seg))
        return out
    return parts(remote) > parts(local)


def _has_dds_url(event) -> bool:
    md = event.mimeData()
    return md.hasUrls() and any(
        u.toLocalFile().lower().endswith('.dds') for u in md.urls()
    )



class ImageViewer(QGraphicsView):
    pixel_hovered = Signal(int, int)
    pixel_left    = Signal()
    file_dropped  = Signal(str)
    activated     = Signal()

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setMouseTracking(True)
        self._scene = QGraphicsScene(self)
        self.setScene(self._scene)
        self._pixmap_item = None
        self._zoom = 1.0
        self._user_zoomed = False
        self._peer: 'ImageViewer | None' = None
        self._syncing = False

        self.setDragMode(QGraphicsView.DragMode.ScrollHandDrag)
        self.setTransformationAnchor(QGraphicsView.ViewportAnchor.AnchorUnderMouse)
        self.setResizeAnchor(QGraphicsView.ViewportAnchor.AnchorUnderMouse)
        self.setRenderHint(QPainter.RenderHint.Antialiasing, False)
        self.setRenderHint(QPainter.RenderHint.SmoothPixmapTransform, False)
        self.setBackgroundBrush(self._make_checker_brush())
        self.setInteractive(True)
        self.setAcceptDrops(True)

        self.horizontalScrollBar().valueChanged.connect(self._on_scroll)
        self.verticalScrollBar().valueChanged.connect(self._on_scroll)

    @staticmethod
    def _make_checker_brush() -> QBrush:
        tile = QPixmap(CHECKER_SIZE * 2, CHECKER_SIZE * 2)
        tile.fill(CHECKER_LIGHT)
        p = QPainter(tile)
        p.fillRect(0, 0, CHECKER_SIZE, CHECKER_SIZE, CHECKER_DARK)
        p.fillRect(CHECKER_SIZE, CHECKER_SIZE, CHECKER_SIZE, CHECKER_SIZE, CHECKER_DARK)
        p.end()
        return QBrush(tile)

    def set_peer(self, peer: 'ImageViewer | None'):
        self._peer = peer

    def _sync_to_peer(self):
        if self._peer and not self._syncing:
            self._peer._apply_sync(
                self.transform(),
                self.horizontalScrollBar().value(),
                self.verticalScrollBar().value(),
            )

    def _apply_sync(self, transform, hval: int, vval: int):
        self._syncing = True
        self._user_zoomed = True
        self.setTransform(transform)
        self.horizontalScrollBar().setValue(hval)
        self.verticalScrollBar().setValue(vval)
        self._syncing = False

    def _on_scroll(self):
        self._sync_to_peer()

    def set_pixmap(self, pixmap: QPixmap):
        self._scene.clear()
        self._pixmap_item = self._scene.addPixmap(pixmap)
        self._scene.setSceneRect(QRectF(pixmap.rect()))

    def heightForWidth(self, width: int) -> int:
        return width

    def hasHeightForWidth(self) -> bool:
        return True

    def fit_in_view(self):
        if self._pixmap_item:
            self._user_zoomed = False
            self.fitInView(self._pixmap_item, Qt.AspectRatioMode.KeepAspectRatio)
            self._sync_to_peer()

    def zoom_actual(self):
        self._user_zoomed = True
        self.resetTransform()
        self._sync_to_peer()

    def resizeEvent(self, event):
        super().resizeEvent(event)
        if not self._user_zoomed:
            self.fit_in_view()

    def mouseMoveEvent(self, event: QMouseEvent):
        super().mouseMoveEvent(event)
        if self._pixmap_item:
            scene_pt = self.mapToScene(event.position().toPoint())
            bounding = self._pixmap_item.boundingRect()
            if bounding.contains(scene_pt):
                self.pixel_hovered.emit(int(scene_pt.x()), int(scene_pt.y()))
            else:
                self.pixel_left.emit()

    def leaveEvent(self, event):
        super().leaveEvent(event)
        self.pixel_left.emit()

    def dragEnterEvent(self, event: QDragEnterEvent):
        if _has_dds_url(event):
            event.acceptProposedAction()
        else:
            event.ignore()

    def dragMoveEvent(self, event):
        if _has_dds_url(event):
            event.acceptProposedAction()
        else:
            event.ignore()

    def dropEvent(self, event: QDropEvent):
        for url in event.mimeData().urls():
            path = url.toLocalFile()
            if path.lower().endswith('.dds'):
                self.file_dropped.emit(path)
                event.acceptProposedAction()
                break

    def wheelEvent(self, event: QWheelEvent):
        self._user_zoomed = True
        factor = 1.25 if event.angleDelta().y() > 0 else 0.8
        self.scale(factor, factor)
        self._sync_to_peer()

    def mousePressEvent(self, event: QMouseEvent):
        self.activated.emit()
        super().mousePressEvent(event)


class ChannelButton(QPushButton):
    def __init__(self, label, key, parent=None):
        super().__init__(label, parent)
        self.key = key
        self.setCheckable(True)
        self.setFixedHeight(26)


class MainWindow(QMainWindow):
    _MAX_RECENT = 10

    # Emitted from the background update-check thread; payload: (latest_version, html_url, notes_or_error, silent)
    _update_signal = Signal(str, str, str, bool)

    def __init__(self):
        super().__init__()
        self.setWindowTitle(APP_TITLE)
        self.setMinimumSize(900, 600)
        self.resize(1100, 700)

        self._mipmaps: list[np.ndarray] = []
        self._info: DDSInfo | None = None
        self._mipmaps2: list[np.ndarray] = []
        self._info2: DDSInfo | None = None
        self._current_mip_l = 0
        self._current_mip_r = 0
        self._channel_l = 'RGB'
        self._channel_r = 'RGB'
        self._last_status = ""
        self._split_mode = False
        self._current_path: str | None = None
        self._current_path2: str | None = None
        self._active_side = 1

        self._build_ui()
        self._build_menu()
        self._build_shortcuts()
        self.setAcceptDrops(True)
        self._restore_geometry()

        # Auto-update: defer the network call so the window paints first.
        self._update_signal.connect(self._on_update_result)
        from PySide6.QtCore import QTimer
        QTimer.singleShot(2000, lambda: self._check_for_updates(silent=True))

    def _build_shortcuts(self):
        from PySide6.QtGui import QShortcut
        QShortcut(QKeySequence(Qt.Key.Key_Left), self,
                  activated=lambda: self._navigate_side(self._active_side, -1))
        QShortcut(QKeySequence(Qt.Key.Key_Right), self,
                  activated=lambda: self._navigate_side(self._active_side, 1))

    # ── UI construction ──────────────────────────────────────────────────────

    def _build_ui(self):
        root = QWidget()
        root_layout = QHBoxLayout(root)
        root_layout.setContentsMargins(0, 0, 0, 0)
        root_layout.setSpacing(0)

        self._splitter = QSplitter(Qt.Orientation.Horizontal)

        left_panel, self.viewer, (self.btn_prev_l, self.btn_del_l, self.btn_next_l) = \
            self._build_viewer_panel(1)
        self.viewer.pixel_hovered.connect(lambda x, y: self._on_pixel_hovered(x, y, 1))
        self.viewer.pixel_left.connect(self._on_pixel_left)
        self.viewer.file_dropped.connect(self.load_file)
        self._splitter.addWidget(left_panel)

        self._right_panel, self.viewer2, (self.btn_prev_r, self.btn_del_r, self.btn_next_r) = \
            self._build_viewer_panel(2)
        self.viewer2.pixel_hovered.connect(lambda x, y: self._on_pixel_hovered(x, y, 2))
        self.viewer2.pixel_left.connect(self._on_pixel_left)
        self.viewer2.file_dropped.connect(self.load_file2)
        self._right_panel.hide()
        self._splitter.addWidget(self._right_panel)

        root_layout.addWidget(self._splitter, stretch=1)

        panel = self._build_side_panel()
        root_layout.addWidget(panel)

        self.setCentralWidget(root)

        self.status = QStatusBar()
        self.setStatusBar(self.status)
        self.status.showMessage("Open a DDS file to begin  (File → Open or drag & drop)")

    def _build_viewer_panel(self, which: int):
        container = QWidget()
        container.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        vbox = QVBoxLayout(container)
        vbox.setContentsMargins(0, 0, 0, 0)
        vbox.setSpacing(2)

        frame = QFrame()
        frame.setFrameShape(QFrame.Shape.NoFrame)
        frame.setObjectName(f"viewerFrame{which}")
        frame.setStyleSheet(
            f"#viewerFrame{which} {{ border: 2px solid transparent; }}"
        )
        frame_layout = QVBoxLayout(frame)
        frame_layout.setContentsMargins(2, 2, 2, 2)
        viewer = ImageViewer()
        viewer.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        viewer.activated.connect(lambda: self._set_active_side(which))
        frame_layout.addWidget(viewer)
        vbox.addWidget(frame, stretch=1)

        bar = QHBoxLayout()
        bar.setContentsMargins(4, 2, 4, 4)
        btn_open = QPushButton("Open…" if which == 1 else "Open Right…")
        btn_prev = QPushButton("◀ Prev")
        btn_del  = QPushButton("Delete")
        btn_next = QPushButton("Next ▶")
        btn_prev.setEnabled(False)
        btn_del.setEnabled(False)
        btn_next.setEnabled(False)
        btn_open.clicked.connect(
            self._open_dialog if which == 1 else self._open_dialog2)
        btn_prev.clicked.connect(lambda: self._navigate_side(which, -1))
        btn_next.clicked.connect(lambda: self._navigate_side(which, 1))
        btn_del.clicked.connect(lambda: self._delete_side(which))
        bar.addWidget(btn_open)
        bar.addWidget(btn_prev)
        bar.addWidget(btn_del)
        bar.addWidget(btn_next)
        vbox.addLayout(bar)

        if which == 1:
            self.btn_open_l = btn_open
            self._frame_l = frame
        else:
            self._frame_r = frame

        return container, viewer, (btn_prev, btn_del, btn_next)

    def _build_side_panel(self) -> QWidget:
        panel = QWidget()
        panel.setFixedWidth(210)
        panel.setSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Expanding)
        layout = QVBoxLayout(panel)
        layout.setContentsMargins(6, 6, 6, 4)

        # ── Info ──────────────────────────────────────────────────────────
        info_box = QGroupBox("Texture Info")
        info_form = QFormLayout(info_box)
        info_form.setSpacing(4)
        self.lbl_size    = QLabel("—")
        self.lbl_fmt     = QLabel("—")
        self.lbl_mips    = QLabel("—")
        self.lbl_alpha   = QLabel("—")
        self.lbl_file    = QLabel("—")
        self.lbl_file.setWordWrap(True)
        info_form.addRow("Size:",    self.lbl_size)
        info_form.addRow("Format:",  self.lbl_fmt)
        info_form.addRow("Mipmaps:", self.lbl_mips)
        info_form.addRow("Alpha:",   self.lbl_alpha)
        info_form.addRow("File:",    self.lbl_file)
        layout.addWidget(info_box)

        # ── Mipmap ────────────────────────────────────────────────────────
        mip_box = QGroupBox("Mipmap Level")
        mip_layout = QVBoxLayout(mip_box)
        self.mip_label = QLabel("Level 0")
        self.mip_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.mip_slider = QSlider(Qt.Orientation.Horizontal)
        self.mip_slider.setMinimum(0)
        self.mip_slider.setMaximum(0)
        self.mip_slider.valueChanged.connect(self._on_mip_changed)
        mip_layout.addWidget(self.mip_label)
        mip_layout.addWidget(self.mip_slider)
        layout.addWidget(mip_box)

        # ── Channels ──────────────────────────────────────────────────────
        chan_box = QGroupBox("Display Channel")
        chan_layout = QVBoxLayout(chan_box)
        self._chan_group = QButtonGroup(self)
        self._chan_buttons: dict[str, ChannelButton] = {}
        for label, key in [("RGBA", "RGBA"), ("RGB (no alpha)", "RGB"),
                            ("Red",  "R"),    ("Green", "G"),
                            ("Blue", "B"),    ("Alpha",  "A")]:
            btn = ChannelButton(label, key)
            self._chan_group.addButton(btn)
            self._chan_buttons[key] = btn
            chan_layout.addWidget(btn)
            btn.clicked.connect(lambda checked, k=key: self._set_channel(k))
        self._chan_buttons['RGB'].setChecked(True)
        layout.addWidget(chan_box)

        # ── Zoom ──────────────────────────────────────────────────────────
        zoom_box = QGroupBox("Zoom")
        zoom_layout = QHBoxLayout(zoom_box)
        btn_fit = QPushButton("Fit")
        btn_100 = QPushButton("1:1")
        btn_fit.clicked.connect(lambda: self._active_viewer().fit_in_view())
        btn_100.clicked.connect(lambda: self._active_viewer().zoom_actual())
        zoom_layout.addWidget(btn_fit)
        zoom_layout.addWidget(btn_100)
        layout.addWidget(zoom_box)

        # ── Compare ───────────────────────────────────────────────────────
        cmp_box = QGroupBox("Compare")
        cmp_layout = QVBoxLayout(cmp_box)
        self.btn_split = QPushButton("Side by Side")
        self.btn_split.setCheckable(True)
        self.btn_split.clicked.connect(self._toggle_split)
        cmp_layout.addWidget(self.btn_split)
        self.chk_mirror = QCheckBox("Mirror zoom && pan")
        self.chk_mirror.setChecked(True)
        self.chk_mirror.setEnabled(False)
        self.chk_mirror.toggled.connect(self._on_mirror_toggled)
        cmp_layout.addWidget(self.chk_mirror)
        layout.addWidget(cmp_box)

        self.chk_confirm_delete = QCheckBox("Always confirm deletion")
        confirm_default = self._settings().value("confirmDelete", True, type=bool)
        self.chk_confirm_delete.setChecked(confirm_default)
        self.chk_confirm_delete.toggled.connect(
            lambda v: self._settings().setValue("confirmDelete", v))
        layout.addWidget(self.chk_confirm_delete)

        layout.addStretch()

        btn_exit = QPushButton("Exit")
        btn_exit.clicked.connect(self.close)
        layout.addWidget(btn_exit)

        return panel

    def _build_menu(self):
        file_menu = self.menuBar().addMenu("&File")

        act_open = QAction("&Open…", self)
        act_open.setShortcut(QKeySequence.StandardKey.Open)
        act_open.triggered.connect(self._open_dialog)
        file_menu.addAction(act_open)

        self._recent_menu = file_menu.addMenu("Open &Recent")
        self._rebuild_recent_menu()

        file_menu.addSeparator()

        act_export = QAction("&Export as PNG…", self)
        act_export.setShortcut("Ctrl+E")
        act_export.triggered.connect(self._export_png)
        file_menu.addAction(act_export)

        file_menu.addSeparator()

        act_exit = QAction("E&xit", self)
        act_exit.setShortcut(QKeySequence.StandardKey.Quit)
        act_exit.triggered.connect(self.close)
        file_menu.addAction(act_exit)

        view_menu = self.menuBar().addMenu("&View")
        act_fit = QAction("Fit to Window\tF", self)
        act_fit.setShortcut("F")
        act_fit.triggered.connect(lambda: self._active_viewer().fit_in_view())
        view_menu.addAction(act_fit)

        act_100 = QAction("Actual Size\t1", self)
        act_100.setShortcut("1")
        act_100.triggered.connect(lambda: self._active_viewer().zoom_actual())
        view_menu.addAction(act_100)

        help_menu = self.menuBar().addMenu("&Help")

        act_readme = QAction("&README…", self)
        act_readme.triggered.connect(self._open_readme)
        help_menu.addAction(act_readme)

        help_menu.addSeparator()

        act_donate = QAction("&Donate via PayPal…", self)
        act_donate.triggered.connect(
            lambda: QDesktopServices.openUrl(QUrl("https://paypal.me/adriaanjutte")))
        help_menu.addAction(act_donate)

        help_menu.addSeparator()

        act_check_updates = QAction("Check for &Updates…", self)
        act_check_updates.triggered.connect(lambda: self._check_for_updates(silent=False))
        help_menu.addAction(act_check_updates)

        act_about = QAction("&About…", self)
        act_about.triggered.connect(self._show_about)
        help_menu.addAction(act_about)


    def _show_about(self):
        QMessageBox.about(self, "About EZ DDS Viewer",
            f"<b>EZ DDS Viewer</b><br>"
            f"Version {APP_VERSION}<br>"
            f"Build {BUILD_HASH} — {BUILD_DATE}<br><br>"
            f"A lightweight DDS texture viewer.<br><br>"
            f'<a href="https://paypal.me/adriaanjutte">Donate via PayPal</a>')

    # ── Auto-update check ───────────────────────────────────────────────────

    def _check_for_updates(self, silent: bool):
        """Query GitHub Releases API for newer version. silent=True suppresses
        'no update' / error dialogs (used on startup)."""
        import threading
        def worker():
            try:
                import json, urllib.request
                req = urllib.request.Request(
                    "https://api.github.com/repos/riaanjutte/EZDDSViewer/releases/latest",
                    headers={"Accept": "application/vnd.github+json",
                             "User-Agent": f"EZDDSViewer/{APP_VERSION}"})
                with urllib.request.urlopen(req, timeout=8) as resp:
                    data = json.loads(resp.read().decode("utf-8"))
                tag = (data.get("tag_name") or "").lstrip("v")
                url = data.get("html_url") or ""
                notes = data.get("body") or ""
                self._update_signal.emit(tag, url, notes, silent)
            except Exception as e:
                self._update_signal.emit("", "", f"ERROR: {e}", silent)
        threading.Thread(target=worker, daemon=True).start()

    def _on_update_result(self, latest: str, url: str, notes: str, silent: bool):
        if notes.startswith("ERROR:"):
            if not silent:
                QMessageBox.warning(self, "Check for Updates",
                    f"Could not contact GitHub:\n{notes[7:].strip()}")
            return
        if not latest:
            if not silent:
                QMessageBox.information(self, "Check for Updates",
                    "Could not determine the latest version.")
            return
        if not _is_newer_version(latest, APP_VERSION):
            if not silent:
                QMessageBox.information(self, "Check for Updates",
                    f"You're up to date.\n\nInstalled: v{APP_VERSION}\nLatest: v{latest}")
            return
        # Skip if user previously dismissed this exact version (startup checks only).
        if silent and self._settings().value("skipUpdateVersion", "") == latest:
            return
        # Truncate notes for the dialog.
        notes_preview = notes.strip()
        if len(notes_preview) > 500:
            notes_preview = notes_preview[:500] + "…"
        box = QMessageBox(self)
        box.setWindowTitle("Update Available")
        box.setIcon(QMessageBox.Icon.Information)
        box.setTextFormat(Qt.TextFormat.RichText)
        box.setText(
            f"<b>A new version is available.</b><br><br>"
            f"Installed: v{APP_VERSION}<br>"
            f"Latest: <b>v{latest}</b><br><br>"
            f"{('<pre style=\"white-space:pre-wrap\">' + notes_preview.replace('<','&lt;') + '</pre>') if notes_preview else ''}"
        )
        btn_open = box.addButton("Download…", QMessageBox.ButtonRole.AcceptRole)
        btn_skip = box.addButton("Skip This Version", QMessageBox.ButtonRole.RejectRole)
        btn_later = box.addButton("Remind Me Later", QMessageBox.ButtonRole.RejectRole)
        box.setDefaultButton(btn_open)
        box.exec()
        clicked = box.clickedButton()
        if clicked is btn_open:
            QDesktopServices.openUrl(QUrl(url))
        elif clicked is btn_skip:
            self._settings().setValue("skipUpdateVersion", latest)
        # btn_later: do nothing — will prompt again next launch

    def _open_readme(self):
        readme = Path(sys.executable).parent / "README.md"
        if not readme.exists():
            readme = Path(__file__).parent / "README.md"
        if readme.exists():
            QDesktopServices.openUrl(QUrl.fromLocalFile(str(readme)))
        else:
            QMessageBox.information(self, "README",
                "README.md was not found next to the executable.\n"
                "It is included in the distribution zip.")

    # ── Recent files ─────────────────────────────────────────────────────────

    def _recent_paths(self) -> list[str]:
        val = self._settings().value("recentFiles", [])
        return val if isinstance(val, list) else []

    def _push_recent(self, path: str):
        paths = [p for p in self._recent_paths() if p != path]
        paths.insert(0, path)
        self._settings().setValue("recentFiles", paths[:self._MAX_RECENT])
        self._rebuild_recent_menu()

    def _rebuild_recent_menu(self):
        self._recent_menu.clear()
        paths = self._recent_paths()
        if not paths:
            self._recent_menu.addAction("(empty)").setEnabled(False)
            return
        for path in paths:
            act = QAction(os.path.basename(path), self)
            act.setToolTip(path)
            act.triggered.connect(lambda checked, p=path: self.load_file(p))
            self._recent_menu.addAction(act)
        self._recent_menu.addSeparator()
        clear_act = QAction("Clear Recent", self)
        clear_act.triggered.connect(self._clear_recent)
        self._recent_menu.addAction(clear_act)

    def _clear_recent(self):
        self._settings().setValue("recentFiles", [])
        self._rebuild_recent_menu()

    # ── File loading ─────────────────────────────────────────────────────────

    def _open_dialog(self):
        last_dir = self._settings().value("lastDir", "")
        path, _ = QFileDialog.getOpenFileName(
            self, "Open DDS File", last_dir,
            "DDS Files (*.dds);;All Files (*.*)",
        )
        if path:
            self._settings().setValue("lastDir", os.path.dirname(path))
            self.load_file(path)

    def _open_dialog2(self):
        last_dir = self._settings().value("lastDir", "")
        path, _ = QFileDialog.getOpenFileName(
            self, "Open Right DDS File", last_dir,
            "DDS Files (*.dds);;All Files (*.*)",
        )
        if path:
            self._settings().setValue("lastDir", os.path.dirname(path))
            self.load_file2(path)

    def load_file(self, path: str):
        try:
            data = Path(path).read_bytes()
            info, mipmaps = parse_dds(data)
        except Exception as exc:
            QMessageBox.critical(self, "Error loading DDS", str(exc))
            return

        self._push_recent(path)
        self._current_path = path
        self._mipmaps = mipmaps
        self._info = info
        self._current_mip_l = 0
        self._channel_l = 'RGB'
        self._update_nav_buttons()

        self.setWindowTitle(f"{APP_TITLE} — {os.path.basename(path)}")
        self._last_status = (
            f"{path}  |  {info.format_name}  |  {info.width}×{info.height}"
            f"  |  {info.mip_count} mip{'s' if info.mip_count != 1 else ''}"
            f"  |  {info.file_size / 1024:.1f} KB"
        )
        self.status.showMessage(self._last_status)
        self._refresh_image()
        self._set_active_side(1)
        self.viewer.fit_in_view()

    def load_file2(self, path: str):
        try:
            data = Path(path).read_bytes()
            info, mipmaps = parse_dds(data)
        except Exception as exc:
            QMessageBox.critical(self, "Error loading DDS", str(exc))
            return
        self._current_path2 = path
        self._mipmaps2 = mipmaps
        self._info2 = info
        self._current_mip_r = 0
        self._channel_r = 'RGB'
        self._update_nav_buttons()
        self._refresh_image2()
        self._set_active_side(2)
        self.viewer2.fit_in_view()

    # ── Folder navigation ─────────────────────────────────────────────────────

    def _folder_dds_files(self, path: str) -> list[str]:
        folder = Path(path).parent
        try:
            files = [p for p in folder.iterdir()
                     if p.is_file() and p.suffix.lower() == '.dds']
        except OSError:
            return []
        files.sort(key=lambda p: p.name.lower())
        return [str(p) for p in files]

    def _side_current(self, which: int) -> str | None:
        return self._current_path if which == 1 else self._current_path2

    def _side_loader(self, which: int):
        return self.load_file if which == 1 else self.load_file2

    def _navigate_side(self, which: int, delta: int):
        current = self._side_current(which)
        if not current:
            return
        files = self._folder_dds_files(current)
        if not files:
            return
        try:
            idx = files.index(current)
        except ValueError:
            idx = 0
            delta = 0
        new_idx = (idx + delta) % len(files)
        self._side_loader(which)(files[new_idx])

    def _delete_side(self, which: int):
        path = self._side_current(which)
        if not path:
            return
        if self.chk_confirm_delete.isChecked():
            reply = QMessageBox.question(
                self, "Delete File",
                f"Delete '{os.path.basename(path)}'?\n\nThis cannot be undone.",
                QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No,
                QMessageBox.StandardButton.No,
            )
            if reply != QMessageBox.StandardButton.Yes:
                return

        files = self._folder_dds_files(path)
        try:
            idx = files.index(path)
        except ValueError:
            idx = -1

        try:
            os.remove(path)
        except OSError as exc:
            QMessageBox.critical(self, "Delete failed", str(exc))
            return

        remaining = [p for p in files if p != path]
        if remaining:
            next_idx = min(idx, len(remaining) - 1) if idx >= 0 else 0
            self._side_loader(which)(remaining[next_idx])
            self.status.showMessage(f"Deleted {os.path.basename(path)}")
        else:
            self._clear_side(which)
            self.status.showMessage(f"Deleted {os.path.basename(path)}  (folder empty)")

    def _clear_side(self, which: int):
        if which == 1:
            self._mipmaps = []
            self._info = None
            self._current_path = None
            self.viewer._scene.clear()
            self.viewer._pixmap_item = None
            self.setWindowTitle(APP_TITLE)
            self._last_status = ""
        else:
            self._mipmaps2 = []
            self._info2 = None
            self._current_path2 = None
            self.viewer2._scene.clear()
            self.viewer2._pixmap_item = None
        self._update_nav_buttons()
        if self._active_side == which:
            self._sync_sidebar_to_active()

    def _update_nav_buttons(self):
        left = bool(self._current_path)
        self.btn_prev_l.setEnabled(left)
        self.btn_next_l.setEnabled(left)
        self.btn_del_l.setEnabled(left)
        right = bool(self._current_path2)
        self.btn_prev_r.setEnabled(right)
        self.btn_next_r.setEnabled(right)
        self.btn_del_r.setEnabled(right)

    def _active_viewer(self) -> 'ImageViewer':
        return self.viewer if self._active_side == 1 else self.viewer2

    def _set_active_side(self, side: int):
        self._active_side = side
        self._update_active_styling()
        self._sync_sidebar_to_active()

    def _update_active_styling(self):
        active_border = "2px solid #3584e4"
        inactive_border = "2px solid transparent"
        if self._split_mode:
            l = active_border if self._active_side == 1 else inactive_border
            r = active_border if self._active_side == 2 else inactive_border
        else:
            l = r = inactive_border
        self._frame_l.setStyleSheet(f"#viewerFrame1 {{ border: {l}; }}")
        self._frame_r.setStyleSheet(f"#viewerFrame2 {{ border: {r}; }}")

    def _sync_sidebar_to_active(self):
        info = self._info if self._active_side == 1 else self._info2
        path = self._current_path if self._active_side == 1 else self._current_path2
        mip_val = self._current_mip_l if self._active_side == 1 else self._current_mip_r
        channel = self._channel_l if self._active_side == 1 else self._channel_r

        if info and path:
            self.lbl_size.setText(f"{info.width} × {info.height}")
            self.lbl_fmt.setText(info.format_name)
            self.lbl_mips.setText(str(info.mip_count))
            self.lbl_alpha.setText("Yes" if info.has_alpha else "No")
            self.lbl_file.setText(os.path.basename(path))
        else:
            self.lbl_size.setText("—")
            self.lbl_fmt.setText("—")
            self.lbl_mips.setText("—")
            self.lbl_alpha.setText("—")
            self.lbl_file.setText("—")

        self.mip_slider.blockSignals(True)
        self._update_mip_range()
        self.mip_slider.setValue(mip_val)
        self.mip_slider.blockSignals(False)
        self._update_mip_label(mip_val)

        if channel in self._chan_buttons:
            self._chan_buttons[channel].setChecked(True)

    # ── Split view ────────────────────────────────────────────────────────────

    def _toggle_split(self, checked: bool):
        self._split_mode = checked
        if checked:
            self._right_panel.show()
            self.btn_open_l.setText("Open Left…")
            self.chk_mirror.setEnabled(True)
            self._splitter.setSizes([self._splitter.width() // 2,
                                     self._splitter.width() // 2])
            self._apply_mirror(self.chk_mirror.isChecked())
        else:
            self._right_panel.hide()
            self.btn_open_l.setText("Open…")
            self.viewer.set_peer(None)
            self.viewer2.set_peer(None)
            self.chk_mirror.setEnabled(False)
            self._set_active_side(1)
        self._update_active_styling()

    def _on_mirror_toggled(self, enabled: bool):
        if self._split_mode:
            self._apply_mirror(enabled)

    def _apply_mirror(self, enabled: bool):
        if enabled:
            self.viewer.set_peer(self.viewer2)
            self.viewer2.set_peer(self.viewer)
        else:
            self.viewer.set_peer(None)
            self.viewer2.set_peer(None)

    # ── Display ──────────────────────────────────────────────────────────────

    def _update_mip_range(self):
        src = self._mipmaps if self._active_side == 1 else self._mipmaps2
        self.mip_slider.setMaximum(max(0, len(src) - 1))

    def _on_mip_changed(self, value: int):
        if self._active_side == 1:
            self._current_mip_l = value
        else:
            self._current_mip_r = value
        self._update_mip_label(value)
        if self._active_side == 1:
            self._refresh_image()
        else:
            self._refresh_image2()

    def _update_mip_label(self, level: int):
        src = self._mipmaps if self._active_side == 1 else self._mipmaps2
        if src:
            clamped = min(level, len(src) - 1)
            h, w = src[clamped].shape[:2]
            self.mip_label.setText(f"Level {level}  ({w}×{h})")

    def _set_channel(self, key: str):
        if self._active_side == 1:
            self._channel_l = key
            self._refresh_image()
        else:
            self._channel_r = key
            self._refresh_image2()

    def _refresh_image(self):
        if not self._mipmaps:
            return
        level = min(self._current_mip_l, len(self._mipmaps) - 1)
        mip = self._mipmaps[level]
        img = self._apply_channel(mip, self._channel_l)
        h, w = img.shape[:2]
        qimg = QImage(img.tobytes(), w, h, w * 4, QImage.Format.Format_RGBA8888)
        self.viewer.set_pixmap(QPixmap.fromImage(qimg))

    def _refresh_image2(self):
        if not self._mipmaps2:
            return
        level = min(self._current_mip_r, len(self._mipmaps2) - 1)
        mip = self._mipmaps2[level]
        img = self._apply_channel(mip, self._channel_r)
        h, w = img.shape[:2]
        qimg = QImage(img.tobytes(), w, h, w * 4, QImage.Format.Format_RGBA8888)
        self.viewer2.set_pixmap(QPixmap.fromImage(qimg))

    def _apply_channel(self, src: np.ndarray, ch: str) -> np.ndarray:
        img = src.copy()
        if ch == 'RGB':
            img[:, :, 3] = 255
        elif ch == 'R':
            r = img[:, :, 0].copy()
            img[:] = 0
            img[:, :, 0] = r
            img[:, :, 3] = 255
        elif ch == 'G':
            g = img[:, :, 1].copy()
            img[:] = 0
            img[:, :, 1] = g
            img[:, :, 3] = 255
        elif ch == 'B':
            b = img[:, :, 2].copy()
            img[:] = 0
            img[:, :, 2] = b
            img[:, :, 3] = 255
        elif ch == 'A':
            a = img[:, :, 3].copy()
            img[:, :, 0] = a
            img[:, :, 1] = a
            img[:, :, 2] = a
            img[:, :, 3] = 255
        return img

    # ── Pixel inspector ──────────────────────────────────────────────────────

    def _on_pixel_hovered(self, x: int, y: int, which: int):
        if which == 1:
            mipmaps = self._mipmaps
            current = self._current_mip_l
        else:
            mipmaps = self._mipmaps2
            current = self._current_mip_r
        if not mipmaps:
            return
        level = min(current, len(mipmaps) - 1)
        mip = mipmaps[level]
        h, w = mip.shape[:2]
        if 0 <= x < w and 0 <= y < h:
            r, g, b, a = mip[y, x]
            self.status.showMessage(
                f"X {x}  Y {y}    R {r}  G {g}  B {b}  A {a}"
                f"    #{r:02X}{g:02X}{b:02X}{a:02X}"
            )

    def _on_pixel_left(self):
        if self._info:
            self.status.showMessage(self._last_status)

    # ── Export ───────────────────────────────────────────────────────────────

    def _export_png(self):
        if self._active_side == 1:
            mipmaps = self._mipmaps
            current_mip = self._current_mip_l
            channel = self._channel_l
            src_path = self._current_path
        else:
            mipmaps = self._mipmaps2
            current_mip = self._current_mip_r
            channel = self._channel_r
            src_path = self._current_path2
        if not mipmaps:
            QMessageBox.information(self, "Export", "No image loaded.")
            return
        stem = os.path.splitext(os.path.basename(src_path))[0] if src_path else "export"
        mip_suffix = f"_mip{current_mip}" if current_mip > 0 else ""
        ch_suffix = f"_{channel}" if channel != "RGB" else ""
        default_name = f"{stem}{mip_suffix}{ch_suffix}.png"
        last_dir = self._settings().value("lastDir", "")
        path, _ = QFileDialog.getSaveFileName(
            self, "Export as PNG", os.path.join(last_dir, default_name),
            "PNG Files (*.png)",
        )
        if not path:
            return
        level = min(current_mip, len(mipmaps) - 1)
        mip = mipmaps[level]
        img = self._apply_channel(mip, channel)
        h, w = img.shape[:2]
        qimg = QImage(img.tobytes(), w, h, w * 4, QImage.Format.Format_RGBA8888)
        if qimg.save(path, "PNG"):
            self.status.showMessage(f"Exported → {path}")
        else:
            QMessageBox.critical(self, "Export failed", f"Could not write {path}")

    # ── Drag & drop (title bar / window edges fallback) ───────────────────────

    def dragEnterEvent(self, event: QDragEnterEvent):
        if _has_dds_url(event):
            event.acceptProposedAction()
        else:
            event.ignore()

    def dragMoveEvent(self, event):
        if _has_dds_url(event):
            event.acceptProposedAction()
        else:
            event.ignore()

    def dropEvent(self, event: QDropEvent):
        for url in event.mimeData().urls():
            path = url.toLocalFile()
            if path.lower().endswith('.dds'):
                self.load_file(path)
                event.acceptProposedAction()
                break

    # ── Window geometry persistence ───────────────────────────────────────────

    def _settings(self) -> QSettings:
        return QSettings("EZDDSViewer", "EZDDSViewer")

    def _restore_geometry(self):
        s = self._settings()
        geom = s.value("geometry")
        if isinstance(geom, QByteArray):
            self.restoreGeometry(geom)

    def closeEvent(self, event):
        self._settings().setValue("geometry", self.saveGeometry())
        super().closeEvent(event)


def main():
    if sys.platform == "win32":
        import ctypes
        ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID("EZDDSViewer.1")

    app = QApplication(sys.argv)
    app.setStyle('Fusion')

    from PySide6.QtGui import QIcon
    base = Path(sys._MEIPASS) if hasattr(sys, '_MEIPASS') else Path(__file__).parent
    app.setWindowIcon(QIcon(str(base / 'icon.ico')))

    win = MainWindow()
    win.show()

    if len(sys.argv) > 1:
        win.load_file(sys.argv[1])

    sys.exit(app.exec())


if __name__ == '__main__':
    main()
